name: workflow

on:
  workflow_dispatch:

jobs:
 first_job:
  name: my first job
  runs-on: ubuntu-latest
  steps:
    - name: My step
      id: step1
      run: echo "My first workflow"
    - name: My second job
      id: shellsetup
      shell: python
      run: print("this step is using python shell")
   
