name: Variables and secrets

env:
 WF_VAR: "Workflow level variable"

on:
 workflow_dispatch:
 push:
  branches: master


jobs:
 test_variables:
   env:
    JOB_VAR: "job level variable"
   name: job to test variables
   runs-on: ubuntu-latest
   steps:
   - name: test variable
     id: stepVar
     env:
      STEP_VAR: "step level variable"
     run: |
      echo ${{ github.actor }}
      echo $GITHUB_TOKEN
      echo $GITHUB_JOB
      echo $WF_VAR
      echo $JOB_VAR
      echo $STEP_VAR
      echo ${{ secrets.A_SECRET}}
      echo ${{  var.CONF_VAR }}
      
       
   
 
